### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jd-apprentice** [josu-dev/onemorechance#21]
# TODO

- [ ] Add a SEO component
- [ ] Enable SSR for all pages except the actual game
- [ ] Add a db to store rooms and decks
- [ ] Add an about page
